=== pdbain/libris/Libris/doc/libris.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ENTITY % boolean "(true|false)">
<!ENTITY % controltype "(radiobutton|checkbox|textbox|textfield|rangefield|enumfield)">
<!ENTITY % usagetype "(newrecord|formdisplay|summarydisplay|formentry|tabledisplay)">
<!ENTITY % groupstructure "(flat|hierarchical)">

<!ELEMENT libris (metadata?, records?)>
<!ENTITY % databaseAttributes	"
	schemaname NMTOKEN #REQUIRED
	schemaversion NMTOKEN #REQUIRED
	schemalocation NMTOKEN #IMPLIED
	databasename NMTOKEN #IMPLIED
	branch NMTOKEN #IMPLIED
	lastchild NMTOKEN #IMPLIED
	date CDATA #IMPLIED" >
	
<!ATTLIST libris  %databaseAttributes; >

<!ELEMENT metadata (schema, layouts)>
<!ELEMENT schema (groupdefs, fielddefs, indexdefs) >

<!ELEMENT fielddefs (enumset*, fielddef*) >

<!ELEMENT fielddef EMPTY>

<!-- Type declaration of the fields in a record 
@attr id Unique ID for the field.  Should start with "f_"
@attr enumset pick values from the a list.  If restricted is not set, the values can be changed.
-->
<!ATTLIST fielddef
	id ID #REQUIRED 
	title CDATA #IMPLIED
	datatype (string|boolean|integer|valuepair|INDEXENTRY|enum) "string"
	enumset IDREF #IMPLIED
	default CDATA #IMPLIED
	valueseparator CDATA #IMPLIED
	restricted %boolean; "false"
	singlevalue %boolean; "false"
	editable %boolean; "true"
	inherit ID #IMPLIED <!-- group ID. Inherit value from parent in this group -->
	>

<!ELEMENT enumset (enumchoice)+>
<!ATTLIST enumset
	id ID #REQUIRED
>
<!ELEMENT enumchoice EMPTY>
<!ATTLIST enumchoice
	id ID #REQUIRED
	value CDATA #IMPLIED
>
	
<!--
Define the indexes in the database
-->
<!ELEMENT groupdefs (groupdef*) >

<!ELEMENT groupdef EMPTY >

<!ATTLIST groupdef
	id ID #REQUIRED
	title CDATA #IMPLIED
	structure %groupstructure; "hierarchical"
>
<!ELEMENT indexdefs (indexdef*) >

<!ELEMENT indexdef (indexfield*) >

<!ELEMENT indexfield EMPTY>

<!ATTLIST indexfield
	id IDREF #REQUIRED
	stoplist %boolean; "false"
	method NMTOKEN "manual"
	>

<!ELEMENT layouts (layout*) >
<!ATTLIST layout
	id ID #REQUIRED
	title CDATA #IMPLIED
	type (table | list | form | text | XML) "table"
		width NMTOKEN #IMPLIED
	height NMTOKEN #IMPLIED
>
	
<!ELEMENT layout ((layoutusage|layoutfield)*) >
<!ELEMENT layoutfield EMPTY>
<!ATTLIST layoutfield
	id IDREF #REQUIRED
	title NMTOKEN #IMPLIED
	return %boolean; "false"
	vspan NMTOKEN #IMPLIED
	hspan NMTOKEN #IMPLIED
	width NMTOKEN #IMPLIED
	height NMTOKEN #IMPLIED
	control %controltype; "textbox"
>

<!ELEMENT layoutusage EMPTY >
<!ATTLIST layoutusage
	usedby %usagetype; #REQUIRED
>

<!--
Records section.
-->
<!ELEMENT records (record*)>
<!ATTLIST records
	lastid NMTOKEN #REQUIRED
>
<!--
Represents a document or a index item
-->
<!ELEMENT record (member*, (field)+)>
<!ATTLIST record
	id ID #REQUIRED 
	revision CDATA #IMPLIED
	replaces IDREF #IMPLIED
>

<!ELEMENT member (affiliation*) >
<!ATTLIST member 
	group CDATA #REQUIRED
	parent ID #IMPLIED
	title CDATA #IMPLIED
>
<!ATTLIST affiliation 
	affiliate ID #REQUIRED
>

<!--
Represents the data in the record
@value for short values
@id points to a <fielddef>
-->
<!ELEMENT field (#PCDATA)*>
<!ATTLIST field
	id IDREF #REQUIRED
	value CDATA #IMPLIED
	extravalue CDATA #IMPLIED
>

=== pdbain/libris/Libris_old/test/Testdatabase1a.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libris SYSTEM "file:///Users/pdbain/Documents/workspaces/libris/libris/doc/libris.dtd">
<libris name="test" date="2005-01-08" version="0.0">
<metadata>
	<schema>
		<fielddefs>
		<enumset id="e_onechoice">
				<enumchoice id="ev_oc" value="onlychoice"/>
		</enumset>
		<enumset id="e_twochoice">
				<enumchoice id="e_tc_1" value="choice1"/>
				<enumchoice id="e_tc_2"  value="choice2"/>
		</enumset>
		<fielddef id="ef2"/>
		<fielddef id="ef1"/>
				<fielddef id="IntField1"/>
				<fielddef id="IntField2"/>
				<fielddef id="BoolField1"/>
				<fielddef id="StringField1"/>
								<fielddef id="StringField2"/>
												</fielddefs>
		<hierarchydefs></hierarchydefs>
				<indexdefs>	
		</indexdefs>
	</schema>
	<layouts></layouts>
	<indexes>
	</indexes>
	<hierarchies></hierarchies>
	</metadata>
	<records lastid="9">
		<record id="r1">
			<field id="StringField1" value="abcdef" />
			<field id="StringField2"> abc defg hijkl mnopqr</field>
			<field id="IntField1" value="12" />
			<field id="IntField2" value="98" />
		</record>
		<record id="r2">
			<field id="StringField1" value="qwerty" />
			<field id="StringField2"> a sd fgh jklz xcvbn</field>
			<field id="IntField1" value="34" />
			<field id="IntField2" value="56" />
		</record>
		<record id="r3">
			<field id="StringField1" value="qwerty" />
			<field id="IntField1" value="34" />
		</record>
		<record id="r4">
			<field id="StringField2">Qazwsx Edcrfv Tgb Yhnujm</field>
			<field id="IntField1" value="3" />
			<field id="IntField2" value="1234567890" />
		</record>
		<record id="r5">
			<field id="StringField1" value="qazwsxedcrfv tgbyhnujmikolp" />
			<field id="StringField2">Qazwsx Edcrfv Tgb Yhnujm</field>
			<field id="IntField1" value="3" />
			<field id="IntField2" value="1234567890" />
		</record>
		<record id="r6">
			<field id="IntField1" value="3" />
			<field id="StringField2"> The quick brown fox jumps over the lazy dog.</field>
			<field id="IntField2" value="1234567890" />
		</record>
		<record id="r7">
			<field id="IntField1" value="3" />
			<field id="StringField2"> The quick brown fox jumps over the lazy dog.</field>
			<field id="IntField2" value="1234567890" />
		</record>
		<record id="r8">
			<field id="BoolField1" value="true" />
			<field id="ef1" value="onlychoice"/>
		</record>
		<record id="r9">
			<field id="BoolField1" value="false" />
			<field id="ef2" value="choice2"/>
		</record>
	</records>
</libris>
